const Types = {
   GET_APP_CONFIGURATION: 'GET_APP_CONFIGURATION',
   GET_APP_CONFIGURATION_SUCCESS: 'GET_APP_CONFIGURATION_SUCCESS',
   GET_APP_CONFIGURATION_FAILURE: 'GET_APP_CONFIGURATION_FAILURE',
}

export default Types
