const Types = {
   GET_PRODUCT: 'GET_PRODUCT',
   GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
   GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',

   UPDATE_PRODUCT: 'UPDATE_PRODUCT',
   UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
   UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',

   GET_TRL_LIST: 'GET_TRL_LIST',
   GET_TRL_LIST_SUCCESS: 'GET_TRL_LIST_SUCCESS',
   GET_TRL_LIST_FAILURE: 'GET_TRL_LIST_FAILURE',
}

export default Types
